# ============================================
# EventFrame 后端配置
# ============================================

# 服务器配置
server:
  host: "0.0.0.0"
  port: 5000
  debug: true

# 事件系统配置
event_system:
  # 事件历史记录最大保留数量
  max_history: 100

  # 后端主动创建事件的默认作用域 (local | broadcast | both)
  default_scope: "local"

  # 从前端接收事件的默认作用域（注意：前端事件不会自动反弹）
  # 这个配置主要影响通过 HTTP API 直接创建的事件
  default_frontend_scope: "local"  # 改为 local，前端事件默认仅后端处理

# 安全策略
security:
  # 禁止前端发送的事件前缀（黑名单）
  blocked_prefixes:
    - "private."
    - "system."
    - "admin."
    - "auth."
    - "internal."

  # 敏感事件前缀（会在广播时警告）
  sensitive_prefixes:
    - "private."
    - "system."
    - "admin."
    - "auth."
    - "internal."

# WebSocket 配置
websocket:
  # CORS 允许的源（生产环境应指定具体域名）
  cors_origins: "*"

  # 传输方式
  transports:
    - "websocket"
    - "polling"

  # 异步模式
  async_mode: "threading"

# 中间件开关
middleware:
  enable_logging: true
  enable_validation: true
  enable_websocket_broadcast: true

# 日志配置
logging:
  verbose: true
  format: "[{timestamp}] Event: {name} | Data: {data}"

# API 配置
api:
  prefix: "/api"
  default_history_limit: 50
  max_history_limit: 200